/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBridgeManagerEvents,
  IBridgeManagerEventsInterface,
} from "../IBridgeManagerEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "governor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "fromBridgeOperator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "toBridgeOperator",
        type: "address",
      },
    ],
    name: "BridgeOperatorUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool[]",
        name: "statuses",
        type: "bool[]",
      },
      {
        indexed: false,
        internalType: "uint96[]",
        name: "voteWeights",
        type: "uint96[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "governors",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "bridgeOperators",
        type: "address[]",
      },
    ],
    name: "BridgeOperatorsAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool[]",
        name: "statuses",
        type: "bool[]",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "bridgeOperators",
        type: "address[]",
      },
    ],
    name: "BridgeOperatorsRemoved",
    type: "event",
  },
];

export class IBridgeManagerEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IBridgeManagerEventsInterface {
    return new utils.Interface(_abi) as IBridgeManagerEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBridgeManagerEvents {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IBridgeManagerEvents;
  }
}
