/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  PCUValidateDoubleSign,
  PCUValidateDoubleSignInterface,
} from "../PCUValidateDoubleSign";

const _abi = [
  {
    inputs: [],
    name: "ErrCallPrecompiled",
    type: "error",
  },
  {
    inputs: [],
    name: "precompileValidateDoubleSignAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PCUValidateDoubleSign__factory {
  static readonly abi = _abi;
  static createInterface(): PCUValidateDoubleSignInterface {
    return new utils.Interface(_abi) as PCUValidateDoubleSignInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PCUValidateDoubleSign {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PCUValidateDoubleSign;
  }
}
