[profile.default]
src = 'src'
out = 'out'
test = 'test'
optimizer = true
optimizer_runs = 200

libs = [
  'lib',
  'node_modules/hardhat',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = '0.8.23'
extra_output = ["devdoc", "userdoc", "storagelayout"]
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version = 'istanbul'
verbosity = 4

[profile.ronin]
evm_version = 'istanbul'

[profile.ethereum]
evm_version = 'shanghai'

[fmt]
line_length = 150
tab_width = 2

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 5_000

[profile.via-ir.fuzz]
runs = 1_000

[profile.min-solc]
solc_version = "0.8.4"

[profile.min-solc.fuzz]
runs = 1_000

[profile.min-solc-via-ir.fuzz]
runs = 1_000

[rpc_endpoints]
ethereum = "https://eth.llamarpc.com"
goerli = "https://ethereum-goerli.publicnode.com"
ronin-mainnet = "https://api-partner.roninchain.com/rpc"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"
localhost = "http://localhost:8545"
