/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SlashBridgeVotingInterface extends utils.Interface {
  functions: {
    "getBridgeVotingSlashingConfigs()": FunctionFragment;
    "getContract(uint8)": FunctionFragment;
    "setBridgeVotingSlashingConfigs(uint256,uint256)": FunctionFragment;
    "setContract(uint8,address)": FunctionFragment;
    "slashBridgeVoting(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBridgeVotingSlashingConfigs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBridgeVotingSlashingConfigs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setContract",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "slashBridgeVoting",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBridgeVotingSlashingConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBridgeVotingSlashingConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashBridgeVoting",
    data: BytesLike
  ): Result;

  events: {
    "BridgeVotingSlashingConfigsUpdated(uint256,uint256)": EventFragment;
    "ContractUpdated(uint8,address)": EventFragment;
    "Slashed(address,uint8,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "BridgeVotingSlashingConfigsUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Slashed"): EventFragment;
}

export type BridgeVotingSlashingConfigsUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { bridgeVotingThreshold: BigNumber; bridgeVotingSlashAmount: BigNumber }
>;

export type BridgeVotingSlashingConfigsUpdatedEventFilter =
  TypedEventFilter<BridgeVotingSlashingConfigsUpdatedEvent>;

export type ContractUpdatedEvent = TypedEvent<
  [number, string],
  { contractType: number; addr: string }
>;

export type ContractUpdatedEventFilter = TypedEventFilter<ContractUpdatedEvent>;

export type SlashedEvent = TypedEvent<
  [string, number, BigNumber],
  { validator: string; slashType: number; period: BigNumber }
>;

export type SlashedEventFilter = TypedEventFilter<SlashedEvent>;

export interface SlashBridgeVoting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SlashBridgeVotingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getBridgeVotingSlashingConfigs(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        bridgeVotingThreshold_: BigNumber;
        bridgeVotingSlashAmount_: BigNumber;
      }
    >;

    getContract(
      contractType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { contract_: string }>;

    setBridgeVotingSlashingConfigs(
      _threshold: BigNumberish,
      _slashAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContract(
      contractType: BigNumberish,
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    slashBridgeVoting(
      _consensusAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getBridgeVotingSlashingConfigs(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      bridgeVotingThreshold_: BigNumber;
      bridgeVotingSlashAmount_: BigNumber;
    }
  >;

  getContract(
    contractType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setBridgeVotingSlashingConfigs(
    _threshold: BigNumberish,
    _slashAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContract(
    contractType: BigNumberish,
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  slashBridgeVoting(
    _consensusAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getBridgeVotingSlashingConfigs(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        bridgeVotingThreshold_: BigNumber;
        bridgeVotingSlashAmount_: BigNumber;
      }
    >;

    getContract(
      contractType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setBridgeVotingSlashingConfigs(
      _threshold: BigNumberish,
      _slashAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setContract(
      contractType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    slashBridgeVoting(
      _consensusAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BridgeVotingSlashingConfigsUpdated(uint256,uint256)"(
      bridgeVotingThreshold?: null,
      bridgeVotingSlashAmount?: null
    ): BridgeVotingSlashingConfigsUpdatedEventFilter;
    BridgeVotingSlashingConfigsUpdated(
      bridgeVotingThreshold?: null,
      bridgeVotingSlashAmount?: null
    ): BridgeVotingSlashingConfigsUpdatedEventFilter;

    "ContractUpdated(uint8,address)"(
      contractType?: BigNumberish | null,
      addr?: string | null
    ): ContractUpdatedEventFilter;
    ContractUpdated(
      contractType?: BigNumberish | null,
      addr?: string | null
    ): ContractUpdatedEventFilter;

    "Slashed(address,uint8,uint256)"(
      validator?: string | null,
      slashType?: null,
      period?: null
    ): SlashedEventFilter;
    Slashed(
      validator?: string | null,
      slashType?: null,
      period?: null
    ): SlashedEventFilter;
  };

  estimateGas: {
    getBridgeVotingSlashingConfigs(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContract(
      contractType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBridgeVotingSlashingConfigs(
      _threshold: BigNumberish,
      _slashAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContract(
      contractType: BigNumberish,
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    slashBridgeVoting(
      _consensusAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBridgeVotingSlashingConfigs(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContract(
      contractType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBridgeVotingSlashingConfigs(
      _threshold: BigNumberish,
      _slashAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContract(
      contractType: BigNumberish,
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    slashBridgeVoting(
      _consensusAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
