name: Run tests
on:
  push:
    branches:
      - mainnet
      - testnet
      - 'feature/*'
      - 'features/*'
  pull_request:
    branches:
      - mainnet
      - testnet
      - 'feature/*'
      - 'features/*'

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          submodules: recursive

      - name: 'Setup Node'
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: v16.16.0

      - name: Github private package token in npmrc
        run: |
          echo "@axieinfinity:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: 'Run install'
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@cb603ca0abb544f301eaed59ac0baf579aa6aecf #v1.0.10

      - name: 'Run Compile'
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: compile

      - name: 'Run Test'
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: test:ci
